
sudo: false
language: scala
scala:
- 2.13.8
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
branches:
  except:
    - master
    services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
