#%RAML 1.0
---

title: Individuals Integration Framework Test Support
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/integration-framework-test-support:
  /individuals/employment/nino/{nino}:
    uriParameters:
      nino:
        description: The employee National Insurance number
        type: string
        example: AA123456D
    post:
      displayName: Create an employment payload
      description: !include docs/create-employment-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: The date that employments data is requested from.
          type: string
          required: true
          example: 01-01-2019
        endDate:
          description: The date that employments data is requested to.
          type: string
          required: true
          example: 01-01-2020
        useCase:
          description: The use case to which the employments data relates.
          type: string
          required: true
          example: LAA-C1 or LAA-C2 or LAA-C3 or LAA-C4 or LSANI-C1 or LSANI-C3 or HMCTS-C2 or HMCTS-C3 or HMCTS-C4 or NICTSEJO-C4
      body:
        application/json:
          schema: !include schemas/create-employment.json
          example: !include examples/create-employment.json
      responses:
        201:
          description: The created employment
          body:
            application/json:
              example: !include examples/create-employment-response.json
              type: !include schemas/create-employment-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/income/sa/nino/{nino}:
    uriParameters:
      nino:
        description: The employee National Insurance number
        type: string
        example: AA123456D

    post:
      displayName: Create a self assessment payload
      description: !include docs/create-self-assessment-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startYear:
          description: The first tax year to be included in the dataset requested.
          type: string
          required: true
          example: '2018'
        endYear:
          description: The last tax year to be included in the dataset requested.
          type: string
          required: true
          example: '2019'
        useCase:
          description: The use case to which the dataset relates.
          type: string
          required: true
          example: LAA-C1 or LAA-C2 or LAA-C3 or LAA-C4 or LSANI-C1 or LSANI-C3 or HMCTS-C2 or HMCTS-C3 or HMCTS-C4 or NICTSEJO-C4
      body:
        application/json:
          schema: !include schemas/create-self-assessment-request.json
          example: !include examples/create-self-assessment-request.json
      responses:
        201:
          description: The created self assessment
          body:
            application/json:
              example: !include examples/create-self-assessment-response.json
              type: !include schemas/create-self-assessment-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/income/paye/nino/{nino}:
    uriParameters:
      nino:
        description: The employee National Insurance number
        type: string
        example: AA123456D

    post:
      displayName: Create a paye income payload
      description: !include docs/create-paye-income-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: The date that paye income data is requested from.
          type: string
          required: true
          example: 01-01-2019
        endDate:
          description: The date that paye income data is requested to.
          type: string
          required: true
          example: 01-01-2020
        useCase:
          description: The use case to which the paye income data relates.
          type: string
          required: true
          example: LAA-C1 or LAA-C2 or LAA-C3 or LAA-C4 or LSANI-C1 or LSANI-C3 or HMCTS-C2 or HMCTS-C3 or HMCTS-C4 or NICTSEJO-C4
      body:
        application/json:
          schema: !include schemas/create-paye-income.json
          example: !include examples/create-paye-income.json
      responses:
        201:
          description: The created paye income
          body:
            application/json:
              example: !include examples/create-paye-income-response.json
              type: !include schemas/create-paye-income-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/tax-credits/nino/{nino}:
    uriParameters:
      nino:
        description: The employee National Insurance number
        type: string
        example: AA123456D
    post:
      displayName: Create a benefits and credits payload
      description: !include docs/create-benefits-and-credits-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: The date that benefits and credits data is requested from.
          type: string
          required: true
          example: 01-01-2019
        endDate:
          description: The date that benefits and credits data is requested to.
          type: string
          required: true
          example: 01-01-2020
        useCase:
          description: The use case to which the benefits and credits data relates.
          type: string
          required: true
          example:  LAA-C1-working-tax-credit or LAA-C2-working-tax-credit or LAA-C3-working-tax-credit or LAA-C1-child-tax-credit
                    or LAA-C2-child-tax-credit or LAA-C3-child-tax-credit or HMCTS-C2-working-tax-credit or HMCTS-C3-working-tax-credit
                    or LSANI-C1-working-tax-credit or LSANI-C3-working-tax-credit
      body:
        application/json:
          schema: !include schemas/create-benefits-and-credits.json
          example: !include examples/create-benefits-and-credits.json
      responses:
        201:
          description: The created employment
          body:
            application/json:
              example: !include examples/create-benefits-and-credits-response.json
              type: !include schemas/create-benefits-and-credits-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/contact/details/nino/{nino}:
    uriParameters:
      nino:
        description: The employee National Insurance number
        type: string
        example: AA123456D
    post:
      displayName: Create a contact details payload
      description: !include docs/create-contact-details-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        useCase:
          description: The use case to which the contact details data relates.
          type: string
          required: true
          example: LAA-C3-residences or LAA-C4-residences or HMCTS-C3-residences or HMCTS-C4-residences or
                   LSANI-C1-residences or LSANI-C4-residences or NICTSEJO-C4-residences or LAA-C4-contact-details or HMCTS-C4-contact-details
      body:
        application/json:
          schema: !include schemas/create-contact-details.json
          example: !include examples/create-contact-details.json
      responses:
        201:
          description: The created contact details
          body:
            application/json:
              example: !include examples/create-contact-details-response.json
              type: !include schemas/create-contact-details-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
