#%RAML 1.0
---

title: Integration Framework Test Support
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals/integration-framework-test-support:
  /individuals/employment/nino/{nino}:
    uriParameters:
      nino:
        description: The employee's National Insurance number.
        type: string
        example: AA123456D
    post:
      displayName: Create employments test data for an individual
      description: !include docs/individuals/create-employment-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: !include docs/individuals/create-employment-data-date-from.md
          type: string
          required: true
          example: 2019-01-01
        endDate:
          description: !include docs/individuals/create-employment-data-date-to.md
          type: string
          required: true
          example: 2020-01-01
        useCase:
          description: !include docs/individuals/use-case-examples/employment-description.md
          type: string
          required: true
          example: LAA-C1
      body:
        application/json:
          schema: !include schemas/individuals/create-employment.json
          example: !include examples/individuals/create-employment.json
      responses:
        201:
          description: The created employment
          body:
            application/json:
              example: !include examples/individuals/create-employment-response.json
              type: !include schemas/individuals/create-employment-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/income/sa/nino/{nino}:
    uriParameters:
      nino:
        description: The employee's National Insurance number.
        type: string
        example: AA123456D

    post:
      displayName: Create Self Assessment income test data for an individual
      description: !include docs/individuals/create-self-assessment-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startYear:
          description: !include docs/individuals/create-self-assessment-first-tax-description.md
          type: string
          required: true
          example: '2018'
        endYear:
          description: !include docs/individuals/create-self-assessment-last-tax-description.md
          type: string
          required: true
          example: '2019'
        useCase:
          description: !include docs/individuals/use-case-examples/income-sa-description.md
          type: string
          required: true
          example: LAA-C1
      body:
        application/json:
          schema: !include schemas/individuals/create-self-assessment-request.json
          example: !include examples/individuals/create-self-assessment-request.json
      responses:
        201:
          description: The created self assessment
          body:
            application/json:
              example: !include examples/individuals/create-self-assessment-response.json
              type: !include schemas/individuals/create-self-assessment-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/income/paye/nino/{nino}:
    uriParameters:
      nino:
        description: The employee's National Insurance number.
        type: string
        example: AA123456D

    post:
      displayName: Create PAYE income test data for an individual
      description: !include docs/individuals/create-paye-income-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: !include docs/individuals/create-paye-data-date-from.md
          type: string
          required: true
          example: 2019-01-01
        endDate:
          description: !include docs/individuals/create-paye-data-date-to.md
          type: string
          required: true
          example: 2020-01-01
        useCase:
          description: !include docs/individuals/use-case-examples/income-paye-description.md
          type: string
          required: true
          example: LAA-C1
      body:
        application/json:
          schema: !include schemas/individuals/create-paye-income.json
          example: !include examples/individuals/create-paye-income.json
      responses:
        201:
          description: The created paye income
          body:
            application/json:
              example: !include examples/individuals/create-paye-income-response.json
              type: !include schemas/individuals/create-paye-income-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/tax-credits/nino/{nino}:
    uriParameters:
      nino:
        description: The employee's National Insurance number.
        type: string
        example: AA123456D
    post:
      displayName: Create benefits and credits test data for an individual
      description: !include docs/individuals/create-benefits-and-credits-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        startDate:
          description: !include docs/individuals/create-benefits-and-credits-data-date-from.md
          type: string
          required: true
          example: 2019-01-01
        endDate:
          description: !include docs/individuals/create-benefits-and-credits-data-date-to.md
          type: string
          required: true
          example: 2020-01-01
        useCase:
          description: !include docs/individuals/use-case-examples/tax-credits-description.md
          type: string
          required: true
          example: LAA-C1-working-tax-credit
      body:
        application/json:
          schema: !include schemas/individuals/create-benefits-and-credits.json
          example: !include examples/individuals/create-benefits-and-credits.json
      responses:
        201:
          description: The created employment
          body:
            application/json:
              example: !include examples/individuals/create-benefits-and-credits-response.json
              type: !include schemas/individuals/create-benefits-and-credits-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /individuals/details/contact/nino/{nino}:
    uriParameters:
      nino:
        description: The employee's National Insurance number.
        type: string
        example: AA123456D
    post:
      displayName: Create details test data for an individual
      description: !include docs/individuals/create-contact-details-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: OAuth 2.0 Bearer Token or server token.
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: Specifies the content-type of the body.
          type: string
          required: true
          example: application/json
      queryParameters:
        useCase:
          description: !include docs/individuals/use-case-examples/details-description.md
          type: string
          required: true
          example: LAA-C3-residences
      body:
        application/json:
          schema: !include schemas/individuals/create-contact-details.json
          example: !include examples/individuals/create-contact-details.json
      responses:
        201:
          description: The created contact details
          body:
            application/json:
              example: !include examples/individuals/create-contact-details-response.json
              type: !include schemas/individuals/create-contact-details-response.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /organisations/self-assessment/return/details/{utr}:
    uriParameters:
      utr:
        description: "A Unique Taxpayer Reference."
        type: string
        required: true
        example: "1234567890"
    post:
      displayName: "Create Self Assessment details test data for an organisation"
      description: !include docs/organisations/create-self-assessment-return-details-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: "OAuth 2.0 Bearer Token or server token."
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: "Specifies the content-type of the body."
          type: string
          required: true
          example: application/json
      body:
        application/json:
          schema: !include schemas/organisations/create-organisations-return-detail.json
          example: !include examples/organisations/create-organisations-return-detail.json
      responses:
        201:
          description: The created contact details
          body:
            application/json:
              type: !include schemas/organisations/create-organisations-return-detail.json
              example: !include examples/organisations/create-organisations-return-detail.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /organisations/corporation-tax/return/details/{utr}:
    uriParameters:
      utr:
        description: "A Unique Taxpayer Reference."
        type: string
        required: true
        example: "1234567890"
    post:
      displayName: "Create Corporation Tax details test data for an organisation"
      description: !include docs/organisations/create-cotax-return-details-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: "OAuth 2.0 Bearer Token or server token."
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: "Specifies the content-type of the body."
          type: string
          required: true
          example: application/json
      body:
        application/json:
          schema: !include schemas/organisations/create-corporation-tax-detail.json
          example: !include examples/organisations/create-corporation-tax-detail.json
      responses:
        201:
          description: The created corporation-tax return details
          body:
            application/json:
              type: !include schemas/organisations/create-corporation-tax-detail.json
              example: !include examples/organisations/create-corporation-tax-detail.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST

  /organisations/employers/employee/counts/createpayload:
    uriParameters:
      utr:
        description: "A Unique Taxpayer Reference."
        type: string
        required: true
        example: "1234567890"
    post:
      displayName: "Create number of employees test data for an organisation"
      description: !include docs/organisations/create-number-of-employees-description.md
      is: [headers.acceptHeader]
      securedBy: [ sec.x-application ]
      headers:
        Authorization:
          description: "OAuth 2.0 Bearer Token or server token."
          type: string
          required: true
          example: Bearer <BEARER_TOKEN>
        Content-Type:
          description: "Specifies the content-type of the body."
          type: string
          required: true
          example: application/json
      body:
        application/json:
          schema: !include schemas/organisations/create-employee-counts.json
          example: !include examples/organisations/create-employee-counts.json
      responses:
        201:
          description: The created employee counts
          body:
            application/json:
              type: !include schemas/organisations/create-employee-counts.json
              example: !include examples/organisations/create-employee-counts.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST